# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the argument for the JAR file
ARG JAR_FILE=target/*.jar

# Copy the JAR file into the container at /app.jar
COPY ${JAR_FILE} app.jar

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Run the JAR file
ENTRYPOINT ["java","-jar","/app.jar"]